version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:3000"
    environment:
      - SQLURI=${SQLURI}
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:8.0
    container_name: hallify_mysql
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always

volumes:
  mysql_data: