version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - hallify-legacy-pb

  hallify-legacy-pb:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: hallify-legacy-pb
    restart: unless-stopped
    ports:
      - "8005:8090"
    volumes:
      - pocketbase-data:/pb_data
      - pocketbase-public:/pb_public
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pocketbase-data:
  pocketbase-public: