name: Code Review (Bun)

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  Formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Check formatting
        run: bun run format:check

  Eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Eslint
        run: bun run lint

  SvelteKit:
    runs-on: ubuntu-latest
    env:
      SQLURI: ${{ vars.SQLURI }}
      PUBLIC_CALENDAR_EXPIRE: ${{ vars.PUBLIC_CALENDAR_EXPIRE }}
      PUBLIC_DEV: ${{ vars.PUBLIC_DEV }}
      PUBLIC_TURNSTILE_TOKEN: ${{ vars.PUBLIC_TURNSTILE_TOKEN }}
      PUBLIC_TURNSTILE_URL: ${{ vars.PUBLIC_TURNSTILE_URL }}
      SECRET_TURNSTILE_TOKEN: ${{ secrets.SECRET_TURNSTILE_TOKEN }}
    strategy:
      matrix:
        bun-version: [latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Check SvelteKit codebase
        run: bun run check
